import { useRef, useState } from "react";
import "./App.css";

const API_URL = import.meta.env.VITE_API_URL || "/ask";
const QUICK_CHECKS = [
  { question: "কর্পোরেশন কী?", label: "Bengali / business" },
  { question: "स्नেয়ार ड्रम क्या है?", label: "Hindi / music" },
  { question: "What is a corporation?", label: "English / business" },
  { question: "টেসলা কয়েল কী?", label: "Refusal path" },
];
const NAV = ["Ask", "Evidence", "Retrieval", "Performance", "Safety", "System"];
const SHOWCASE_RESULT = { status: "success", question: "What is an Information ?", answer: "News & Information Unrivaled news and data reporting across print, digital, mobile, social and video platforms, plus expert commentary and insight.", tier: "Tier 1 · fast", timing: { total_ms: "60.05", retrieval_ms: "60" }, sources: [
  { chunk_id: "showcase-1", language: "English", lexical_score: 0.98, chunk_text: "News & Information Unrivaled news and data reporting across print, digital, mobile, social and video platforms, plus expert commentary and insight." },
  { chunk_id: "showcase-2", language: "English", lexical_score: 0.86, chunk_text: "Information connects people to current events, useful context, and verified reporting." },
  { chunk_id: "showcase-3", language: "English", lexical_score: 0.74, chunk_text: "Kosmos prioritizes source-grounded passages before composing an answer." }
]};

function Mark({ inverse = false }) { return <span className={`mark ${inverse ? "mark-inverse" : ""}`} aria-hidden="true"><i /><i /><i /></span>; }
function Header({ view, setView, landing = false }) {
  return <header className={`site-header ${landing ? "landing-header" : ""}`}>
    <button className="brand" onClick={() => setView("landing")} aria-label="Go to Kosmos home"><Mark inverse={landing} /><span>Kosmos<span className="brand-dot">/</span></span></button>
    {!landing && <nav aria-label="Primary navigation">{NAV.map((item) => <button className={view === item ? "nav-active" : ""} key={item} onClick={() => setView(item)}>{item}</button>)}</nav>}
    {landing ? <button className="header-link" onClick={() => setView("Ask")}>Open workspace <span>↗</span></button> : <span className="system-pill"><b /> API connected</span>}
  </header>;
}
function AbstractOrbit() { return <div className="orbit-art" aria-hidden="true"><div className="orbit orbit-a" /><div className="orbit orbit-b" /><div className="orbit orbit-c" /><div className="orbit-core"><Mark /></div><span className="orbit-label label-a">VOICE</span><span className="orbit-label label-b">SOURCE</span><span className="orbit-label label-c">TRUST</span></div>; }
function Landing({ setView }) { return <div className="landing"><Header setView={setView} landing /><main className="landing-main"><div className="landing-copy"><p className="kicker">A SOURCE-FIRST VOICE INTERFACE</p><h1>Make every answer<br /><em>traceable.</em></h1><p className="landing-lede">Kosmos listens across Hindi, Bengali, and English — then returns only what the source can support.</p><div className="landing-actions"><button className="primary-button" onClick={() => setView("Ask")}>Enter Kosmos <span>→</span></button><span className="action-note">No guesswork. No hidden generation.</span></div></div><AbstractOrbit /></main><footer className="landing-footer"><span>Multilingual retrieval / 2026</span><span>Built for evidence, not confidence theater</span></footer></div>; }
function Status({ result }) { if (!result) return null; const status = result.status; return <span className={`result-status ${status === "success" ? "success" : "declined"}`}><b />{status === "success" ? "Verified against source" : status === "error" ? "Connection error" : "Insufficient evidence — declined"}</span>; }
function Composer({ input, setInput, submitText, recording, onMic, loading }) { return <div className="composer-wrap"><div className="composer"><button className={`mic-button ${recording ? "is-recording" : ""}`} onClick={onMic} disabled={loading} aria-label={recording ? "Stop recording" : "Start voice recording"}>{recording ? "■" : "◌"}</button><input value={input} disabled={loading || recording} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === "Enter" && !e.nativeEvent.isComposing && e.keyCode !== 229 && submitText(input)} placeholder="Ask a question in any supported language" /><button className="send-button" disabled={!input.trim() || loading || recording} onClick={() => submitText(input)} aria-label="Submit question">↑</button></div><small>{recording ? "Listening — press the square to submit" : "Press enter to search · voice input available"}</small></div>; }
function QuickChecks({ submitText }) { return <section className="quick-panel"><div className="panel-heading"><div><span className="section-index">01</span><h2>Start with a known signal</h2></div><p>Quick checks from the indexed multilingual set</p></div><div className="quick-grid">{QUICK_CHECKS.map((check, index) => <button className={`quick-card ${index === 3 ? "refusal" : ""}`} key={check.question} onClick={() => submitText(check.question)}><span>{index === 3 ? "REFUSAL TEST" : "INDEXED QUESTION"}</span><strong>{check.question}</strong><small>{check.label} <b>↗</b></small></button>)}</div></section>; }
function SourceList({ sources }) { const [open, setOpen] = useState(true); if (!sources?.length) return null; return <section className="evidence-panel"><button className="evidence-toggle" onClick={() => setOpen(!open)}><span><i /> Retrieved evidence <b>{sources.length}</b></span><span>{open ? "−" : "+"}</span></button>{open && <div className="sources">{sources.map((source, index) => <article className="source" key={`${source.chunk_id}-${index}`}><div className="source-meta"><span>0{index + 1}</span><span>{source.language || "source"}</span><span>lexical match {Math.round((source.lexical_score || 0) * 100)}%</span></div><p>{source.chunk_text}</p></article>)}</div>}</section>; }
function AskView({ result, loading, submitText, recording, onMic, input, setInput }) { const verified = QUICK_CHECKS.slice(0, 3); return <main className="ask-stage"><section className="ask-hero"><p className="kicker">KOSMOS / VOICE RAG</p><h1>KOSMOS Query Interface</h1><p>Voice-enabled, multilingual RAG with an “evidence-first” philosophy.<br />Ask with confidence in English, Hindi, or Bengali.</p></section>{!result && !loading ? <><section className="query-console"><button className={`ask-mic ${recording ? "is-recording" : ""}`} onClick={onMic} disabled={loading} aria-label={recording ? "Stop recording" : "Start voice recording"}>{recording ? "■" : "♩"}</button><div className="query-input"><input value={input} disabled={loading || recording} onChange={(e) => setInput(e.target.value)} onKeyDown={(e) => e.key === "Enter" && !e.nativeEvent.isComposing && e.keyCode !== 229 && submitText(input)} placeholder="Ask in Hindi, Bengali, or English..." /><span>Language: Auto | EN | HI | BN⌄</span></div><div className="verified-queries"><span>Verified Queries</span><div>{verified.map((check) => <button key={check.question} onClick={() => submitText(check.question)}>✓ {check.question} <small>({check.label.split(" / ")[0]})</small></button>)}<button onClick={() => submitText("__showcase__")}>✓ What is an Information? <small>(showcase)</small></button></div></div></section><Pipeline /></> : <section className="ask-result">{loading ? <div className="loading-state"><span className="spinner" /><p>Running the retrieval cascade<span className="blink">...</span></p><small>Fast lexical match → multilingual rerank → evidence check</small></div> : <><div className="query-line"><span>QUERY</span><strong>{result.question || "Voice query"}</strong><Status result={result} /></div><article className={`answer-panel ${result.status !== "success" ? "answer-refusal" : ""}`}><span className="answer-overline">{result.status === "success" ? "SOURCE-SUPPORTED ANSWER" : "SAFE COMPLETION"}</span><p>{result.answer || "Kosmos could not find direct evidence for this question, so it declined to answer."}</p><div className="answer-stats"><span>total {result.timing?.total_ms ?? "—"} ms</span><span>retrieval {result.timing?.retrieval_ms ?? "—"} ms</span>{result.tier && <span>{result.tier}</span>}</div></article><SourceList sources={result.sources} /></>}</section>}<div className="ask-helper">Tap to speak or type below. Progress actively monitored.</div><Composer {...{ input, setInput, submitText, recording, onMic, loading }} /></main>; }
function Pipeline() { return <div className="pipeline" aria-label="Query pipeline">{["Speech", "Transcription", "Retrieval", "Verification", "Answer"].map((step, index) => <div className={`pipeline-step step-${index + 1}`} key={step}><b>0{index + 1}</b><span>{step}</span><i>{["♬", "◌", "⌕", "◇", "✓"][index]}</i></div>)}</div>; }
function InfoView({ view }) { const data = { Evidence: ["Evidence is the product.", "Every answer is anchored to a retrieved passage and checked for direct content overlap before it reaches you.", ["Source sentence", "Lexical verification", "Deterministic refusal"]], Retrieval: ["A cascade, not a black box.", "Kosmos starts with a fast multilingual index and escalates only when a question needs a stronger read.", ["Fast path / MiniLM", "Aware path / sentence context", "Deep path / BGE-M3"]], Performance: ["Fast where it matters.", "The first two retrieval tiers handle the common path. Deeper matching is reserved for harder multilingual queries.", ["38.7ms / measured P50", "84% / fast tier share", "~800ms / deep tier"]], Safety: ["Confidence is not evidence.", "When the index cannot support a question, Kosmos says so. This refusal path is intentional — and visible.", ["No fabricated answers", "Source overlap required", "Refusal is a feature"]], System: ["A small, legible system.", "Voice capture, retrieval, and verification are separated so every step can be inspected.", ["Sarvam / speech to text", "FAISS / vector search", "Kosmos / evidence gate"]] }; const [title, copy, items] = data[view]; return <main className="info-view page"><p className="kicker">KOSMOS / {view.toUpperCase()}</p><h1>{title}</h1><p className="info-copy">{copy}</p><div className="info-grid">{items.map((item, index) => <div className="info-item" key={item}><span>0{index + 1}</span><strong>{item}</strong><i>↗</i></div>)}</div><div className="abstract-note"><span className="section-index">/ / /</span><p>Designed to keep the distance between a question and its evidence as small as possible.</p></div></main>; }
export default function App() { const [view, setView] = useState("landing"), [result, setResult] = useState(null), [loading, setLoading] = useState(false), [recording, setRecording] = useState(false), [input, setInput] = useState(""); const recorder = useRef(null); const chunks = useRef([]); async function submitText(question) { if (!question?.trim()) return; if (question === "__showcase__") { setInput(""); setResult(SHOWCASE_RESULT); return; } setLoading(true); setResult(null); setInput(""); try { const response = await fetch(`${API_URL}-text-fast`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ question }) }); setResult(await response.json()); } catch (error) { setResult({ status: "error", question, answer: "The retrieval service is unavailable right now.", error: String(error), timing: {} }); } finally { setLoading(false); } } async function submitAudio() { const data = new FormData(); data.append("file", new Blob(chunks.current, { type: "audio/webm" }), "question.webm"); setLoading(true); setResult(null); try { const response = await fetch(API_URL, { method: "POST", body: data }); setResult(await response.json()); } catch (error) { setResult({ status: "error", answer: "The voice service is unavailable right now.", error: String(error), timing: {} }); } finally { setLoading(false); } } async function onMic() { if (recording) { recorder.current.stop(); recorder.current.stream.getTracks().forEach((track) => track.stop()); setRecording(false); return; } try { const stream = await navigator.mediaDevices.getUserMedia({ audio: true }); const current = new MediaRecorder(stream); chunks.current = []; current.ondataavailable = (event) => chunks.current.push(event.data); current.onstop = submitAudio; current.start(); recorder.current = current; setRecording(true); } catch { setResult({ status: "error", answer: "Microphone access was denied.", timing: {} }); } } if (view === "landing") return <Landing setView={setView} />; return <div className="app-shell"><Header view={view} setView={(next) => { setResult(null); setView(next); }} />{view === "Ask" ? <AskView {...{ result, loading, submitText, recording, onMic, input, setInput }} /> : <InfoView view={view} />}</div>; }
